### ISSUE TITLE
训练时间，迭代次数

### ISSUE THREAD

**Issue by DA21S321D** [langyo/hakurei_reimu_detector#1]
你好，请问训练一次需要多长时间呢，是要等到99/99吗，我中途停止生成的模型在测试图片中没有红框圈出，
![image](https://github.com/langyo/hakurei_reimu_detector/assets/56549016/65539071-1820-4099-967a-a06e1684d6e8)

**Comment by DA21S321D** [comment]
![image](https://github.com/langyo/hakurei_reimu_detector/assets/56549016/c99ba770-4e36-40a8-af57-d4fb67b313e1)
tafei他非常慢，我一共自己用labelimg圈了157张图片，顺便问下这个warning对结果有影响吗

**Comment by langyo** [comment]
有关第一个问题，是的，得跑完它规划的所有子任务，子任务数量一般是你训练用的所有图片的数量的两倍左右；在训练与测试结束后，终端会告诉你识别结果的概览图片放在了哪个文件夹中，记得在宿主机以docker cp指令把图片拿出来看就好

有关第二个问题，这似乎是超出了每轮识别的限制时间长度——还是能用的，但这时候你最好检查一下你的显卡是否配置正确，别搞成拿CPU跑了

**Comment by DA21S321D** [comment]
而且好像我在用cpu跑，显卡没有cuda占用选项，我可能没有下载，请问可以用显卡跑吗

**Comment by DA21S321D** [comment]
> 
我刚刚也觉得在用cpu跑，我是第一次接触docker该怎么设置显卡呢

**Comment by langyo** [comment]
> 而且好像我在用cpu跑，显卡没有cuda占用选项，我可能没有下载，请问可以用显卡跑吗

尽量不要使用CPU跑，你刚刚的warning应该就是CPU识别超时了

建议找台有nvidia显卡的机器，并且最低需要4GB显存

一般来说wsl2下的docker会自动检查是否拥有GPU可以调用，这时候需要确保你已经安装了CUDA驱动，只能在有N卡的机器安装

**Comment by DA21S321D** [comment]
![image](https://github.com/langyo/hakurei_reimu_detector/assets/56549016/44b251a2-5aa4-44c0-bccf-ceaf7b1fff93)
成功了，感谢
